### ISSUE TITLE
Устаревший illuminate

### ISSUE THREAD

**Issue by ProklUng** [Uru-ruru/bitrix-mvc#1]
Основная проблема пакета arrilot/models в текущем (брошенном) виде - устарелость использумых версий Illuminate. Laravel 5, когда уже вовсю цветет седьмой и даже восьмой? Ох и ах. Это легко фиксится - заменой устаревших хэлперов (см. https://github.com/ProklUng/bitrix-models). Удалось завести на 6 и 7 версии, 8 - не проверял.

Ваш пакет таким образом - прямиком завися от оригинала - сразу обретает эту же родовую травму.

**Comment by Uru-ruru** [comment]
Спасибо большое. Это как раз был следующий шаг и вы его упростили.

**Comment by ProklUng** [comment]
Кстати, зря Вы залочили строго на восьмую версию. Например, существуют варианты, когда не получается использовать даже седьмую. Например, в рамках вот этой популярной сборки - https://github.com/regiomedia/bitrix-project. Там, с небольшими изменениями, удается установить седьмую, в общем случае шестую версию.

Лок на восьмой сразу отрубает большую часть потенциальных пользователей. IMHO достаточно поставить ^6.0 и все.

**Comment by Uru-ruru** [comment]
Тогда может лучше так: >=6.0

**Comment by ProklUng** [comment]
Да, самое то IMHO.
